# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/1___study/FPGA/The edge of the recognition/zuiyong/zuiyong/program/ov7725/ov7725/ov7725.srcs/sources_1/ip/wzj/wzj.xci
# IP: The module: 'wzj' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/1___study/FPGA/The edge of the recognition/zuiyong/zuiyong/program/ov7725/ov7725/ov7725.srcs/sources_1/ip/wzj/wzj_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wzj'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: f:/1___study/FPGA/The edge of the recognition/zuiyong/zuiyong/program/ov7725/ov7725/ov7725.srcs/sources_1/ip/wzj/wzj.xci
# IP: The module: 'wzj' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/1___study/FPGA/The edge of the recognition/zuiyong/zuiyong/program/ov7725/ov7725/ov7725.srcs/sources_1/ip/wzj/wzj_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wzj'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
