# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {F:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.cache/wt} [current_project]
set_property parent.project_path {F:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  {f:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/Digital-Design-Lab-master/Chapter_12/Digital_camera/files/HDL_source/IP_Catalog}
  {f:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/HDL_source}
  {f:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program}
} [current_project]
add_files -quiet {{F:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/sources_1/ip/IICctrl_0/IICctrl_0.dcp}}
set_property used_in_implementation false [get_files {{F:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/sources_1/ip/IICctrl_0/IICctrl_0.dcp}}]
add_files -quiet {{f:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp}}
set_property used_in_implementation false [get_files {{f:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp}}]
add_files -quiet {{F:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/sources_1/ip/cam_ov7670_ov7725_0/cam_ov7670_ov7725_0.dcp}}
set_property used_in_implementation false [get_files {{F:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/sources_1/ip/cam_ov7670_ov7725_0/cam_ov7670_ov7725_0.dcp}}]
add_files -quiet {{f:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp}}
set_property used_in_implementation false [get_files {{f:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp}}]
add_files -quiet {{F:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/sources_1/ip/ov7725_regData_0/ov7725_regData_0.dcp}}
set_property used_in_implementation false [get_files {{F:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/sources_1/ip/ov7725_regData_0/ov7725_regData_0.dcp}}]
add_files -quiet {{F:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/sources_1/ip/vga_0/vga_0.dcp}}
set_property used_in_implementation false [get_files {{F:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/sources_1/ip/vga_0/vga_0.dcp}}]
add_files -quiet {{f:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/sources_1/ip/sqrt/sqrt.dcp}}
set_property used_in_implementation false [get_files {{f:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/sources_1/ip/sqrt/sqrt.dcp}}]
add_files -quiet {{f:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.dcp}}
set_property used_in_implementation false [get_files {{f:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.dcp}}]
read_verilog -library xil_defaultlib {
  {F:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/sources_1/new/code_change.v}
  {F:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/sources_1/new/display_scan.v}
  {F:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/sources_1/new/clk_divide.v}
  {F:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/sources_1/new/ram_read1.v}
  {F:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/sources_1/new/ram_read_1.v}
  {F:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/sources_1/new/design_1.v}
  {F:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/sources_1/new/design_1_wrapper.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{F:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/constrs_1/imports/Constraint/cam_bram_vga.xdc}}
set_property used_in_implementation false [get_files {{F:/1___study/1___study/FPGA/The edge of the recognition/new/new/program/program/ov7725/ov7725/ov7725.srcs/constrs_1/imports/Constraint/cam_bram_vga.xdc}}]


synth_design -top design_1_wrapper -part xc7a35tcpg236-1


write_checkpoint -force -noxdef design_1_wrapper.dcp

catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
